### ISSUE TITLE
CalDAV link changes after grain restart

### ISSUE THREAD

**Issue by mapleoin** [synchrone/sandstorm-radicale#19]
The CalDAV sync API URI seems to change every time there is a grain restart on sandstorm. This makes syncing/using the caldav server from another interface impossible AFAIU. It seems that I would need to keep the sandstorm webapp open all the time so the radicale grain doesn't get restarted.

**Comment by synchrone** [comment]
Sync API URI contains HTTP Basic username-dependant dynamic subdomain in it. It is expected that it would be changing not only with grain restart, but with Sync dialog re-open, since a new pair of credentials is requested from Sandstorm every time. If those credentials are not used in 5 minutes after generation - they are invalidated.

However, credentials that were generated and used (!) within 5 minutes of opening that dialog remain valid and are visible in the web-keys dropdown. They also remain valid if the grain was put to sleep, and access to such API endpoint actually wakes up the grain.

**Comment by mapleoin** [comment]
Awesome. Thank you for the clarification. I did have an active web-key in the dropdown, but there seems to be no way to see the password for that after it's been created. So I had to setup the CalDAV integration again in my client using a new URI and username/password.
