### ISSUE TITLE
Syncronisation Radical for Sandstorm and Thunderbird 52.6.0 (32bits) lightning 5.4.6

### ISSUE THREAD

**Issue by sebschopf** [synchrone/sandstorm-radicale#36]
It's impossible to active agenda with Thunderbird.

All other works but one nope... He is syncronised with CalDAV for android but impossible with Thunderbird.
I have try to activ with an other Thunderburd (linux Mint and Window) but same...
![capture](https://user-images.githubusercontent.com/4943792/37203827-45a383d8-238f-11e8-9a27-c97830b2c79f.PNG)

![screenshot-oasis sandstorm io-2018-03-09-11-35-03](https://user-images.githubusercontent.com/4943792/37203592-72cafaea-238e-11e8-8844-f3fc958b3656.png)

**Comment by garrison** [comment]
I have been experiencing greyed calendars in Thunderbird for the past week (approximately) as well.  I strongly suspect this is related to the recent change in Sandstorm which [made the new HTTP gateway on by default](https://github.com/sandstorm-io/sandstorm/blob/master/CHANGELOG.md#v0226-2018-03-03).  My Android devices all sync successfully to the calendar, but my devices using Thunderbird all show greyed out calenders.

It wasn't until reading the comments on [this Thunderbird issue](https://bugzilla.mozilla.org/show_bug.cgi?id=992340) that I began to suspect this lower-level change may be related.  (I am not certain that this thread is directly relevant here, though.)

Pinging @kentonv.

**Comment by kentonv** [comment]
Tracked this down. Apparently Thunderbird starts off assuming the host has no authentication required and jumps straight to doing a PROPFIND request. Due to a bug in the new gateway code, it responds with a 403 status, whereas for a GET it would respond with a 401. The 401 status code is what triggers Thunderbird to prompt the user for a password, and then use that password.

I'll have a fix up in probably an hour or two. I also had a report that old versions of Mercurial weren't working with the new gateway. Hopefully it's the same issue. Once both are fixed I'll push a release.

**Comment by kentonv** [comment]
(Update: I'm rolling a few other things into this release, but it will be out before the end of the day.)
